--
-- PostgreSQL database new version
--

-- PostGis extensions --
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;

-- Default options --
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = off;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;
SET row_security = off;

--
-- Name: gist_geometry_ops; Type: OPERATOR FAMILY; Schema: public; Owner: _root
--

CREATE OPERATOR FAMILY public.gist_geometry_ops USING gist;
ALTER OPERATOR FAMILY public.gist_geometry_ops USING gist OWNER TO _root;

SET default_tablespace = '';
SET default_with_oids = false;

--
-- Name: data_exchange; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.data_exchange (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    lieu character varying(256),
    commune character varying(100),
    altitude integer,
    gps character varying(15) NOT NULL,
    massif character varying(50),
    geom public.geometry,
    unite character varying DEFAULT 'PG38'::character varying,
    session character varying,
    utm character(20),
    tgi character varying(100),
	PRIMARY KEY (id)
);

--
-- Name: lst_meteo; Type: TABLE; Schema: public
--
CREATE TABLE public.lst_meteo (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    meteo character varying(100) NOT NULL,
	PRIMARY KEY (id)
);

--
-- Name: lst_vent; Type: TABLE; Schema: public
--
CREATE TABLE public.lst_vent (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    vent character varying(100) NOT NULL, 
	PRIMARY KEY (id)
);

--
-- Name: lst_inter; Type: TABLE; Schema: public
--
CREATE TABLE public.lst_inter (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    inter character varying(100) NOT NULL,
	PRIMARY KEY (id)
);

--
-- Name: lst_zone; Type: TABLE; Schema: public
--
CREATE TABLE public.lst_zone (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    zone character varying(100) NOT NULL,
	PRIMARY KEY (id)
);

--
-- Name: lst_activites; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.lst_activites (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    categorie character varying(100) NOT NULL,
    activites character varying(100) NOT NULL,
	PRIMARY KEY (id)
);

--
-- Name: lst_blessures; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.lst_blessures (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    categorie character varying(256) NOT NULL,
    blessures character varying(256) NOT NULL,
	PRIMARY KEY (id)
);


--
-- Name: lst_communes; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.lst_communes (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    dept character varying(256) NOT NULL,
    commune character varying(60) NOT NULL,
	PRIMARY KEY (id)
);


--
-- Name: lst_etat; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.lst_etat (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    etat character varying(256) NOT NULL,
	PRIMARY KEY (id)
);


--
-- Name: lst_evacuation; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.lst_evacuation (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    lieu_evacuation character varying(256) NOT NULL, 
    PRIMARY KEY (id)
);

--
-- Name: lst_massifs; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.lst_massifs (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    massifs character varying(256) NOT NULL,
    geom public.geometry,
	PRIMARY KEY (id)
);

--
-- Name: lst_lieux; Type: TABLE; Schema: public; Owner: admin
-- Rappel: certains massifs peuvent être ajoutés comme as --> les ajouter au préalable dans la table lst_massifs
--
CREATE TABLE public.lst_lieux (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    lieu character varying(256) NOT NULL,
    massif_id integer NOT NULL,
    commune_id integer NOT NULL,
    altitude integer NOT NULL,
    gps character varying(15) NOT NULL,
    geom public.geometry, 
	PRIMARY KEY (id),
	FOREIGN KEY (massif_id) REFERENCES public.lst_massifs (id) ON DELETE SET NULL,
	FOREIGN KEY (commune_id) REFERENCES public.lst_communes (id) ON DELETE SET NULL
);

--
-- Name: lst_nationalites; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.lst_nationalites (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    pays character varying(256) NOT NULL,
    PRIMARY KEY (id)
);

--
-- Name: lst_personnels; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.lst_personnels (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    ordre integer NOT NULL,
    type character varying(256),
    organisme character varying(256),
    lieu character varying(256),
    nom character varying(256),
    prenom character varying(256),
    grade character varying(3),
    tph character varying(12),
    op boolean, 
    PRIMARY KEY (id)
);

--
-- Name: num_fiche_annee; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.num_fiche_annee
    START WITH 1
    INCREMENT BY 1
    MINVALUE 0
    NO MAXVALUE
    CACHE 1
    CYCLE;


ALTER TABLE public.num_fiche_annee OWNER TO admin;

--
-- Name: tab_alerte; Type: TABLE; Schema: public
--
CREATE TABLE public.tab_alerte (
    secours_id integer GENERATED BY DEFAULT AS IDENTITY,
    alerte_gdh timestamp without time zone,
    alerte_moyen character varying(10),
    alerte_origine character varying(20),
	chk_conf3 smallint,
    "chk_confCodis" character varying(20),
    "chk_confSamu" character varying(20),
    "chk_confCorg" character varying(20),
    "chk_confPghm" character varying(20),
    "chk_confRequerant" character varying(20),
    chk_tph smallint,
    tph_intl character varying(30),
    tph_nat character varying(30),
    requerant character varying(60),
	inter_id integer,
    PRIMARY KEY (secours_id), 
	FOREIGN KEY (inter_id) REFERENCES public.lst_inter (id) ON DELETE SET NULL
);

--
-- Name: localisation_alerte; Type: TABLE; Schema: public
--
CREATE TABLE public.localisation_alerte (
    id integer GENERATED BY DEFAULT AS IDENTITY,
	secours_id integer NOT NULL,
	lieu_id integer,
    loc_complement character varying(256),
    loc_utm character varying,
    PRIMARY KEY (id), 
	FOREIGN KEY (secours_id) REFERENCES public.tab_alerte (secours_id) ON DELETE CASCADE, 
	FOREIGN KEY (lieu_id) REFERENCES public.lst_lieux (id) ON DELETE SET NULL
);

--
-- Name: gestion_secours; Type: TABLE; Schema: public
--
CREATE TABLE public.gestion_secours (
    id integer GENERATED BY DEFAULT AS IDENTITY,
	secours_id integer NOT NULL,
	gp_id integer,
    planton_id integer,
    pv integer,
	op_id integer,
	chk_bsm smallint,
    chk_cro smallint,
    chk_pulsar smallint,
	caravane smallint,
	fiche smallint DEFAULT nextval('public.num_fiche_annee'::regclass),
    PRIMARY KEY (id), 
	FOREIGN KEY (secours_id) REFERENCES public.tab_alerte (secours_id) ON DELETE CASCADE, 
	FOREIGN KEY (gp_id) REFERENCES public.lst_personnels (id) ON DELETE SET NULL, 
	FOREIGN KEY (planton_id) REFERENCES public.lst_personnels (id) ON DELETE SET NULL,
	FOREIGN KEY (op_id) REFERENCES public.lst_personnels (id) ON DELETE SET NULL	
);

--
-- Name: accident; Type: TABLE; Schema: public
--
CREATE TABLE public.accident (
    id integer GENERATED BY DEFAULT AS IDENTITY,
	secours_id integer NOT NULL,
	acc_gdh timestamp without time zone,
    activite_id integer,
    acc_sexe character varying(1),
    blessure_id integer,
    acc_bilan character varying(1),
    acc_rsgts text,
    rech_vl text,
    rech_pers text,
    chk_rech smallint,
    chk_hemorragie smallint,
    meteo_id integer,
    vent_id integer,
	chk_pci smallint,
    chk_hc smallint,
    PRIMARY KEY (id), 
	FOREIGN KEY (secours_id) REFERENCES public.tab_alerte (secours_id) ON DELETE CASCADE,
	FOREIGN KEY (activite_id) REFERENCES public.lst_activites (id) ON DELETE SET NULL,
	FOREIGN KEY (meteo_id) REFERENCES public.lst_meteo (id) ON DELETE SET NULL,
	FOREIGN KEY (vent_id) REFERENCES public.lst_vent (id) ON DELETE SET NULL
);

--
-- Name: renseignement; Type: TABLE; Schema: public
--
CREATE TABLE public.renseignement (
    id integer GENERATED BY DEFAULT AS IDENTITY,
	secours_id integer NOT NULL,
	rsgts_divers text,
    rsgts_circonstances text,
    rsgts_check smallint,
    rsgts_professionnel text, 
	rsgts_mp text,
	chk_mprelevage smallint,
    chk_mpcollier smallint,
    chk_mpattelle smallint,
    chk_mpked smallint,
    chk_mpperche smallint,
    chk_mptreuillage smallint,
    chk_mpmam smallint,
    chk_mpo2 smallint,
    chk_mpmid smallint,
	suivi_id integer,
	PRIMARY KEY (id),
	FOREIGN KEY (secours_id) REFERENCES public.tab_alerte (secours_id) ON DELETE CASCADE,
	FOREIGN KEY (suivi_id) REFERENCES public.lst_personnels (id) ON DELETE SET NULL
);


CREATE VIEW public.localisation AS
SELECT 
localisation_alerte.secours_id,
localisation_alerte.lieu_id,
lst_lieux.lieu, 
lst_lieux.massif_id,
lst_massifs.massifs, 
lst_massifs.geom as geom_massif,
lst_lieux.commune_id,
lst_communes.dept, 
lst_communes.commune,
lst_lieux.altitude, 
lst_lieux.gps, 
lst_lieux.geom,
localisation_alerte.loc_complement,
localisation_alerte.loc_utm
FROM ((public.localisation_alerte LEFT JOIN public.lst_lieux ON localisation_alerte.lieu_id=lst_lieux.id)
LEFT JOIN lst_communes ON lst_lieux.commune_id=lst_communes.id)
LEFT JOIN lst_massifs ON lst_lieux.massif_id=lst_massifs.id;

CREATE VIEW public.accidentBlessure AS
  SELECT
  accident.secours_id,
  accident.acc_gdh,
  accident.activite_id,
  lst_activites.categorie as categorie_activite,
  lst_activites.activites,
  accident.acc_sexe,
  accident.blessure_id,
  lst_blessures.categorie as categorie_blessure,
  lst_blessures.blessures,
  accident.acc_bilan,
  accident.acc_rsgts,
  accident.rech_vl,
  accident.rech_pers,
  accident.chk_rech,
  accident.chk_hemorragie,
  accident.meteo_id,
  accident.vent_id,
  accident.chk_pci, 
  accident.chk_hc
	FROM (public.accident LEFT JOIN public.lst_blessures ON accident.blessure_id=lst_blessures.id) LEFT JOIN lst_activites ON accident.activite_id=lst_activites.id;
	
	CREATE VIEW public.secours AS
SELECT *
	FROM ((public.tab_alerte NATURAL LEFT JOIN public.accidentBlessure) NATURAL LEFT JOIN public.localisation) NATURAL LEFT JOIN public.renseignement;

--
-- Name: tab_config; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tab_config (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    annee integer,
    unite character varying(256),
    code_unite character varying(10),
    commune_id integer, 
	PRIMARY KEY (id), 
	FOREIGN KEY (commune_id) REFERENCES public.lst_communes (id) ON DELETE SET NULL
);


--
-- Name: tab_deroulement; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.tab_deroulement (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    secours_id integer NOT NULL,
	deroulement_gdh timestamp without time zone[] NOT NULL,
    deroulement_texte text[],
	PRIMARY KEY (id), 
	FOREIGN KEY (secours_id) REFERENCES public.tab_alerte (secours_id) ON DELETE CASCADE
);

--
-- Name: tab_moyens; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.tab_moyens (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    secours_id integer,
    personnel_id integer,
	PRIMARY KEY (id), 
	FOREIGN KEY (secours_id) REFERENCES public.tab_alerte (secours_id) ON DELETE CASCADE,
	FOREIGN KEY (personnel_id) REFERENCES public.lst_personnels (id) ON DELETE SET NULL
);

--
-- Name: tab_victimes; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.tab_victimes (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    secours_id integer,
    nom character varying(256),
    prenom character varying(256),
    sexe character varying(1),
    naissance_date timestamp without time zone,
    naissance_lieu character varying(256),
    nationalite character varying(256),
    filiation character varying(256),
    adresse character varying(256),
    adresse_commune character varying(256),
    tph character varying(256),
    profession character varying(256),
    etat_id integer,
    blessures character varying(256),
    evacuation_id integer, 
	PRIMARY KEY (id), 
	FOREIGN KEY (secours_id) REFERENCES public.tab_alerte (secours_id) ON DELETE CASCADE,
	FOREIGN KEY (evacuation_id) REFERENCES public.lst_evacuation (id) ON DELETE SET NULL,
	FOREIGN KEY (etat_id) REFERENCES public.lst_etat (id) ON DELETE SET NULL
);


-- Ownership --
ALTER TABLE public.accident OWNER TO admin;
ALTER TABLE public.data_exchange OWNER TO admin;
ALTER TABLE public.gestion_secours OWNER TO admin;
ALTER TABLE public.localisation_alerte OWNER TO admin;
ALTER TABLE public.lst_activites OWNER TO admin;
ALTER TABLE public.lst_blessures OWNER TO admin;
ALTER TABLE public.lst_communes OWNER TO admin;
ALTER TABLE public.lst_etat OWNER TO admin;
ALTER TABLE public.lst_evacuation OWNER TO admin;
ALTER TABLE public.lst_inter OWNER TO admin;
ALTER TABLE public.lst_lieux OWNER TO admin;
ALTER TABLE public.lst_massifs OWNER TO admin;
ALTER TABLE public.lst_meteo OWNER TO admin;
ALTER TABLE public.lst_nationalites OWNER TO admin;
ALTER TABLE public.lst_personnels OWNER TO admin;
ALTER TABLE public.lst_vent OWNER TO admin;
ALTER TABLE public.lst_zone OWNER TO admin;
ALTER TABLE public.renseignement OWNER TO admin;
ALTER TABLE public.tab_alerte OWNER TO admin;
ALTER TABLE public.tab_config OWNER TO admin;
ALTER TABLE public.tab_deroulement OWNER TO admin;
ALTER TABLE public.tab_moyens OWNER TO admin;
ALTER TABLE public.tab_victimes OWNER TO admin;

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO admin;

