--
-- PostgreSQL database version 1.0.0
-- Nouvelle structure
--

-- PostGis extensions --
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;

-- Default options --
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = off;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;
SET row_security = off;

--
-- Name: gist_geometry_ops; Type: OPERATOR FAMILY; Schema: public; Owner: _root
--

CREATE OPERATOR FAMILY public.gist_geometry_ops USING gist;
ALTER OPERATOR FAMILY public.gist_geometry_ops USING gist OWNER TO _root;

SET default_tablespace = '';
SET default_with_oids = false;

--
-- Name: asm_data_exchange; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.asm_data_exchange (
    de_id integer GENERATED BY DEFAULT AS IDENTITY,
    de_lieu character varying(256),
    de_commune character varying(100),
    de_altitude integer,
    de_gps character varying(15) NOT NULL,
    de_massif character varying(50),
    de_geom public.geometry,
    de_unite character varying DEFAULT 'PG38'::character varying,
    de_session character varying,
    de_utm character(20),
    de_tgi character varying(100),
	PRIMARY KEY (de_id)
);

comment on table public.asm_data_exchange is 'Lieu ajouté via l''outil cartographique';
comment on column public.asm_data_exchange.de_id is 'Clé primaire, identifiant de la data_exchange';
comment on column public.asm_data_exchange.de_lieu is 'Nom du lieu';
comment on column public.asm_data_exchange.de_commune is 'Nom de la commune';
comment on column public.asm_data_exchange.de_altitude is 'Altitude du lieu';
comment on column public.asm_data_exchange.de_gps is 'Coordonnées GPS';
comment on column public.asm_data_exchange.de_massif is 'Nom du massif';
comment on column public.asm_data_exchange.de_geom is 'Coordonnées géométriques';
comment on column public.asm_data_exchange.de_unite is 'Unite';
comment on column public.asm_data_exchange.de_session is 'Session';
comment on column public.asm_data_exchange.de_utm is 'Universal Transverse Mercator';
comment on column public.asm_data_exchange.de_tgi is 'Tribunal de Grande Instance';

--
-- Name: asm_condition_meteo; Type: TABLE; Schema: public
--
CREATE TABLE public.asm_condition_meteo (
    cm_id integer GENERATED BY DEFAULT AS IDENTITY,
    cm_description character varying(100) NOT NULL,
	PRIMARY KEY (cm_id)
);

comment on table public.asm_condition_meteo is 'Condition météorologique';
comment on column public.asm_condition_meteo.cm_id is 'Clé primaire, identifiant de la condition météorologique';
comment on column public.asm_condition_meteo.cm_description is 'Description de la condition météorologique';

--
-- Name: asm_condition_vent; Type: TABLE; Schema: public
--
CREATE TABLE public.asm_etat_vent (
    ev_id integer GENERATED BY DEFAULT AS IDENTITY,
    ev_description character varying(100) NOT NULL, 
	PRIMARY KEY (ev_id)
);

comment on table public.asm_etat_vent is 'Etat du vent';
comment on column public.asm_etat_vent.ev_id is 'Clé primaire, identifiant de l''état du vent';
comment on column public.asm_etat_vent.ev_description is 'Description de l''état du vent';

--
-- Name: lst_inter; Type: TABLE; Schema: public
--
CREATE TABLE public.asm_intervenant (
    in_id integer GENERATED BY DEFAULT AS IDENTITY,
    in_nom character varying(100) NOT NULL,
	PRIMARY KEY (in_id)
);

comment on table public.asm_intervenant is 'Intervenant';
comment on column public.asm_intervenant.in_id is 'Clé primaire, identifiant de l''intervenant';
comment on column public.asm_intervenant.in_nom is 'Nom de l''intervenant';

--
-- Name: lst_zone; Type: TABLE; Schema: public
--
CREATE TABLE public.asm_zone_geographique (
    zg_id integer GENERATED BY DEFAULT AS IDENTITY,
    zg_nom character varying(100) NOT NULL,
	PRIMARY KEY (zg_id)
);

comment on table public.asm_zone_geographique is 'Zone géographique';
comment on column public.asm_zone_geographique.zg_id is 'Clé primaire, identifiant de la zone géographique';
comment on column public.asm_zone_geographique.zg_nom is 'Nom de la zone géographique';

--
-- Name: lst_activites; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.asm_activite_sportive (
    as_id integer GENERATED BY DEFAULT AS IDENTITY,
    as_categorie character varying(100) NOT NULL,
    as_nom character varying(100) NOT NULL,
	PRIMARY KEY (as_id)
);

comment on table public.asm_activite_sportive is 'Activité sportive';
comment on column public.asm_activite_sportive.as_id is 'Clé primaire, identifiant de l''activité sportive';
comment on column public.asm_activite_sportive.as_categorie is 'Catégorie de l''activité sportive';
comment on column public.asm_activite_sportive.as_nom is 'Nom de l''activité sportive';

--
-- Name: lst_blessures; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.asm_blessure (
    bl_id integer GENERATED BY DEFAULT AS IDENTITY,
    bl_categorie character varying(256) NOT NULL,
    bl_nom character varying(256) NOT NULL,
	PRIMARY KEY (bl_id)
);

comment on table public.asm_blessure is 'Blessure';
comment on column public.asm_blessure.bl_id is 'Clé primaire, identifiant de la blessure';
comment on column public.asm_blessure.bl_categorie is 'Catégorie de la blessure';
comment on column public.asm_blessure.bl_nom is 'Nom (description) de la blessure';


--
-- Name: lst_communes; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.asm_commune (
    co_id integer GENERATED BY DEFAULT AS IDENTITY,
    co_departement character varying(256) NOT NULL,
    co_nom character varying(60) NOT NULL,
	PRIMARY KEY (co_id)
);

comment on table public.asm_commune is 'LCommune française';
comment on column public.asm_commune.co_id is 'Clé primaire, identifiant de la commune';
comment on column public.asm_commune.co_departement is 'Département de la commune';
comment on column public.asm_commune.co_nom is 'Nom de la commune';

--
-- Name: lst_etat; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.asm_etat_clinique (
    ec_id integer GENERATED BY DEFAULT AS IDENTITY,
    ec_description character varying(256) NOT NULL,
	PRIMARY KEY (ec_id)
);

comment on table public.asm_etat_clinique is 'Etat clinique';
comment on column public.asm_etat_clinique.ec_id is 'Clé primaire, identifiant de l''etat clinique';
comment on column public.asm_etat_clinique.ec_description is 'Description de l''état clinique';

--
-- Name: lst_evacuation; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.asm_lieu_evacuation (
    le_id integer GENERATED BY DEFAULT AS IDENTITY,
    le_nom character varying(256) NOT NULL, 
    PRIMARY KEY (le_id)
);

comment on table public.asm_lieu_evacuation is 'Lieu d''évacuation des victimes';
comment on column public.asm_lieu_evacuation.le_id is 'Clé primaire, identifiant du lieu d''évacuation';
comment on column public.asm_lieu_evacuation.le_nom is 'Nom du ieu d''évacuation';

--
-- Name: lst_massifs; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.asm_massif (
    ma_id integer GENERATED BY DEFAULT AS IDENTITY,
    ma_nom character varying(256) NOT NULL,
    ma_geom public.geometry,
	PRIMARY KEY (ma_id)
);

comment on table public.asm_massif is 'Massif montagneux';
comment on column public.asm_massif.ma_id is 'Clé primaire, identifiant du massif';
comment on column public.asm_massif.ma_nom is 'Nom du massif';
comment on column public.asm_massif.ma_geom is 'Coordonnées géométriques du massif';

--
-- Name: lst_lieux; Type: TABLE; Schema: public; Owner: admin
-- Rappel: certains massifs peuvent être ajoutés comme as --> les ajouter au préalable dans la table lst_massifs
--
CREATE TABLE public.asm_lieu (
    li_id integer GENERATED BY DEFAULT AS IDENTITY,
    li_nom character varying(256) NOT NULL,
    li_fk_massif_id integer NOT NULL,
    li_fk_commune_id integer NOT NULL,
    li_altitude integer NOT NULL,
    li_gps character varying(15) NOT NULL,
	PRIMARY KEY (li_id),
	FOREIGN KEY (li_fk_massif_id) REFERENCES public.asm_massif (ma_id) ON DELETE SET NULL,
	FOREIGN KEY (li_fk_commune_id) REFERENCES public.asm_commune (co_id) ON DELETE SET NULL
);

comment on table public.asm_lieu is 'Lieu connu';
comment on column public.asm_lieu.li_id is 'Clé primaire, identifiant du lieu';
comment on column public.asm_lieu.li_nom is 'Nom du lieu';
comment on column public.asm_lieu.li_fk_massif_id is 'Clé étrangère, ID du massif associé';
comment on column public.asm_lieu.li_fk_commune_id is 'Clé étrangère, ID de la commune associée';
comment on column public.asm_lieu.li_altitude is 'Altitude (m) du lieu';
comment on column public.asm_lieu.li_gps is 'Coordonnées GPS du lieu';

--
-- Name: lst_nationalites; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.asm_nationalite (
    na_id integer GENERATED BY DEFAULT AS IDENTITY,
    na_nom character varying(256) NOT NULL,
    PRIMARY KEY (na_id)
);

comment on table public.asm_nationalite is 'Nationalité';
comment on column public.asm_nationalite.na_id is 'Clé primaire, identifiant de la nationalité';
comment on column public.asm_nationalite.na_nom is 'Nom de la nationalité';

--
-- Name: lst_personnels; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.asm_entite_secours (
    es_id integer GENERATED BY DEFAULT AS IDENTITY,
    es_type character varying(256),
    es_organisme character varying(256),
    es_lieu character varying(256),
    es_nom character varying(256),
    es_prenom character varying(256),
    es_grade character varying(3),
    es_tph character varying(12),
    es_op boolean, 
    PRIMARY KEY (es_id)
);

comment on table public.asm_entite_secours is 'Entité de secours (personnel soignant, secouristes ou équipages, hélicoptère)';
comment on column public.asm_entite_secours.es_id is 'Clé primaire, Identifiant de l''entité de secours';
comment on column public.asm_entite_secours.es_type is 'Médecin, secouriste, équipage, hélicoptère, équipe cynophile, ou autre';
comment on column public.asm_entite_secours.es_organisme is 'Organisme auquel appartient l''entité de secours';
comment on column public.asm_entite_secours.es_lieu is 'Location de l''entité de secours';
comment on column public.asm_entite_secours.es_nom is 'Nom de l''entité de secours';
comment on column public.asm_entite_secours.es_prenom is 'Prénom du personnel';
comment on column public.asm_entite_secours.es_grade is 'Grade du personnel';
comment on column public.asm_entite_secours.es_tph is 'Numéro de téléphone';
comment on column public.asm_entite_secours.es_op is 'Officier de permanence (booléen)';


CREATE SEQUENCE public.num_fiche_annee
    START WITH 1
    INCREMENT BY 1
    MINVALUE 0
    NO MAXVALUE
    CACHE 1
    CYCLE;


ALTER TABLE public.num_fiche_annee OWNER TO admin;

--
-- Name: tab_alerte; Type: TABLE; Schema: public
--
CREATE TABLE public.asm_alerte_general (
    ag_id integer GENERATED BY DEFAULT AS IDENTITY,
    ag_gdh timestamp without time zone,
    ag_moyen character varying(10),
    ag_origine character varying(20),
	ag_conference boolean,
    ag_confCodis boolean,
    ag_confSamu boolean,
    ag_confCorg boolean,
    ag_confPghm boolean,
    ag_confRequerant boolean,
    ag_telephone character varying(30),
    ag_telInt boolean,
    ag_telNat boolean,
    ag_requerant character varying(60),
	ag_fk_intervenant_id integer,
    PRIMARY KEY (ag_id), 
	FOREIGN KEY (ag_fk_intervenant_id) REFERENCES public.asm_intervenant (in_id) ON DELETE SET NULL
);

comment on table public.asm_alerte_general is 'Informations générales d''une alerte (section ''Alerte'' de l''onglet ''Alerte'')';
comment on column public.asm_alerte_general.ag_id is 'Clé primaire, Identifiant de l''alerte';
comment on column public.asm_alerte_general.ag_gdh is 'GDP (Groupe-Date-Heure) de l''alerte';
comment on column public.asm_alerte_general.ag_moyen is 'Moyen par lequel l''alerte a été donnée';
comment on column public.asm_alerte_general.ag_origine is 'Origine de l''alerte (organisme)';
comment on column public.asm_alerte_general.ag_conference is '(Booléen) S''il y a eu conférence entre les différents organismes de secours';
comment on column public.asm_alerte_general.ag_confCodis is '(Booléen) CODIS présent lors de la conférence';
comment on column public.asm_alerte_general.ag_confSamu is '(Booléen) SAMU présent lors de la conférence';
comment on column public.asm_alerte_general.ag_confCorg is '(Booléen) CORG présent lors de la conférence';
comment on column public.asm_alerte_general.ag_confPghm is '(Booléen) PGHM présent lors de la conférence';
comment on column public.asm_alerte_general.ag_confRequerant is '(Booléen) Requérant présent lors de la conférence';
comment on column public.asm_alerte_general.ag_telephone is 'Numéro de téléphone utilisé pour donner l''alerte';
comment on column public.asm_alerte_general.ag_telInt is '(Booléen) Numéro international';
comment on column public.asm_alerte_general.ag_telNat is '(Booléen) Numéro national';
comment on column public.asm_alerte_general.ag_requerant is 'Requérant de l''alerte';
comment on column public.asm_alerte_general.ag_fk_intervenant_id is 'Clé étrangère, ID de l''intervenant';

--
-- Name: localisation_alerte; Type: TABLE; Schema: public
--
CREATE TABLE public.asm_alerte_localisation (
    al_id integer GENERATED BY DEFAULT AS IDENTITY,
	al_fk_alerte_general_id integer NOT NULL,
	al_fk_lieu_id integer,
    al_complement character varying(256),
    al_utm character varying,
    PRIMARY KEY (al_id), 
	FOREIGN KEY (al_fk_alerte_general_id) REFERENCES public.asm_alerte_general (ag_id) ON DELETE CASCADE, 
	FOREIGN KEY (al_fk_lieu_id) REFERENCES public.asm_lieu (li_id) ON DELETE SET NULL
);

comment on table public.asm_alerte_localisation is 'Localisation de l''alerte (section ''Localisation'' de l''onglet ''Alerte'')';
comment on column public.asm_alerte_localisation.al_id is 'Clé primaire, identifiant de la localisation de l''alerte';
comment on column public.asm_alerte_localisation.al_fk_alerte_general_id is 'Clé étrangère, ID de l''alerte associée';
comment on column public.asm_alerte_localisation.al_fk_lieu_id is 'Clé étrangère, ID du lieu de l''alerte';
comment on column public.asm_alerte_localisation.al_complement is 'Complément de localisation';
comment on column public.asm_alerte_localisation.al_utm is 'Localisation UTM';

--
-- Name: gestion_secours; Type: TABLE; Schema: public
--
CREATE TABLE public.asm_alerte_gestion_secours (
    ags_id integer GENERATED BY DEFAULT AS IDENTITY,
	ags_fk_alerte_general_id integer NOT NULL,
	ags_fk_entite_secours_id_cs integer,
    ags_fk_entite_secours_id_planton integer,
    ags_pv integer,
	ags_fk_entite_secours_id_op integer,
	ags_bsm boolean,
    ags_cro boolean,
    ags_pulsar boolean,
	ags_fiche smallint DEFAULT nextval('public.num_fiche_annee'::regclass),
    PRIMARY KEY (ags_id), 
	FOREIGN KEY (ags_fk_alerte_general_id) REFERENCES public.asm_alerte_general (ag_id) ON DELETE CASCADE, 
	FOREIGN KEY (ags_fk_entite_secours_id_cs) REFERENCES public.asm_entite_secours (es_id) ON DELETE SET NULL, 
	FOREIGN KEY (ags_fk_entite_secours_id_planton) REFERENCES public.asm_entite_secours (es_id) ON DELETE SET NULL,
	FOREIGN KEY (ags_fk_entite_secours_id_op) REFERENCES public.asm_entite_secours (es_id) ON DELETE SET NULL	
);


comment on table public.asm_alerte_gestion_secours is 'Informations sur la gestion du secours (section ''Gestion du secours'' de l''onglet ''Alerte'')';
comment on column public.asm_alerte_gestion_secours.ags_id is 'Clé primaire, identifiant de la gestion du secours';
comment on column public.asm_alerte_gestion_secours.ags_fk_alerte_general_id is 'Clé étrangère, ID de l''alerte associée';
comment on column public.asm_alerte_gestion_secours.ags_fk_entite_secours_id_cs is 'Clé étrangère, ID du chef de salle (anciennement ''gs'')';
comment on column public.asm_alerte_gestion_secours.ags_fk_entite_secours_id_planton is 'Clé étrangère, ID du planton';
comment on column public.asm_alerte_gestion_secours.ags_pv is 'Numéro de PV';
comment on column public.asm_alerte_gestion_secours.ags_fk_entite_secours_id_op is 'Clé étrangère, ID de l''officier de permanence';
comment on column public.asm_alerte_gestion_secours.ags_bsm is 'BSM';
comment on column public.asm_alerte_gestion_secours.ags_cro is 'CRO';
comment on column public.asm_alerte_gestion_secours.ags_pulsar is 'PULS';
comment on column public.asm_alerte_gestion_secours.ags_fiche is 'Numéro de fiche';
--
-- Name: accident; Type: TABLE; Schema: public
--
CREATE TABLE public.asm_alerte_accident (
    acc_id integer GENERATED BY DEFAULT AS IDENTITY,
	acc_fk_alerte_general_id integer NOT NULL,
	acc_gdh timestamp without time zone,
    acc_fk_activite_id integer,
    acc_sexe character varying(1),
    acc_fk_blessure_id integer,
    acc_bilan character varying(1),
	acc_recherche boolean,
    acc_recherche_vehicule text,
    acc_recherche_personne text,
    acc_hemorragie boolean,
    acc_fk_condition_meteo_id integer,
    acc_fk_etat_vent_id integer,
	acc_pci boolean,
    acc_hc boolean,
	PRIMARY KEY (acc_id),
	FOREIGN KEY (acc_fk_alerte_general_id) REFERENCES public.asm_alerte_general (ag_id) ON DELETE CASCADE,
	FOREIGN KEY (acc_fk_activite_id) REFERENCES public.asm_activite_sportive (as_id) ON DELETE SET NULL,
	FOREIGN KEY (acc_fk_blessure_id) REFERENCES public.asm_blessure (bl_id) ON DELETE SET NULL,
	FOREIGN KEY (acc_fk_condition_meteo_id) REFERENCES public.asm_condition_meteo (cm_id) ON DELETE SET NULL,
	FOREIGN KEY (acc_fk_etat_vent_id) REFERENCES public.asm_etat_vent (ev_id) ON DELETE SET NULL
);


comment on table public.asm_alerte_accident is 'Informations sur l''accident (section ''Accident'' de l''onglet ''Alerte'')';
comment on column public.asm_alerte_accident.acc_id is 'Clé primaire, identifiant de l''accident';
comment on column public.asm_alerte_accident.acc_id is 'Clé étrangère, ID de l''alerte associée';
comment on column public.asm_alerte_accident.acc_gdh is ' GDH (Groupe Date-Heure) de l''accident';
comment on column public.asm_alerte_accident.acc_fk_activite_id is 'Clé étrangère, ID de l''activité sportive associée à l''accident';
comment on column public.asm_alerte_accident.acc_sexe is 'Sexe de la victime';
comment on column public.asm_alerte_accident.acc_fk_blessure_id  is 'Clé étrangère, ID de la blessure';
comment on column public.asm_alerte_accident.acc_bilan is 'Bilan vital';
comment on column public.asm_alerte_accident.acc_recherche is '(Booléen) La victime est recherchée';
comment on column public.asm_alerte_accident.acc_recherche_vehicule is 'Informations sur le/les véhicule(s) de la personne recherchée';
comment on column public.asm_alerte_accident.acc_recherche_personne is 'Description de la personne recherchée';
comment on column public.asm_alerte_accident.acc_hemorragie is ' (Booléen) hémorragie';
comment on column public.asm_alerte_accident.acc_fk_condition_meteo_id is 'Clé étrangère, ID de la condition météorologique';
comment on column public.asm_alerte_accident.acc_fk_etat_vent_id is 'Clé étrangère, ID de l''état venteux';
comment on column public.asm_alerte_accident.acc_pci is '(Booléen) PCI';
comment on column public.asm_alerte_accident.acc_hc is '(Booléen) Haute Cinétique';

--
-- Name: renseignement; Type: TABLE; Schema: public
--
CREATE TABLE public.asm_renseignement (
    rg_id integer GENERATED BY DEFAULT AS IDENTITY,
	rg_fk_alerte_general_id integer NOT NULL,
    rg_circonstances text,
    rg_sensible boolean,
	rg_mesures_prises text,
	rg_mp_relevage boolean,
    rg_mp_collier boolean,
    rg_mp_attelle boolean,
    rg_mp_ked boolean,
    rg_mp_perche boolean,
    rg_mp_treuillage boolean,
    rg_mp_mam boolean,
    rg_mp_o2 boolean,
    rg_mp_mid boolean,
	rg_fk_entite_secours_id integer,
	PRIMARY KEY (rg_id),
	FOREIGN KEY (rg_fk_alerte_general_id) REFERENCES public.asm_alerte_general (ag_id) ON DELETE CASCADE,
	FOREIGN KEY (rg_fk_entite_secours_id) REFERENCES public.asm_entite_secours (es_id) ON DELETE SET NULL
);


comment on table public.asm_renseignement is 'Renseignements sur l''alerte (onglet''Renseignements'')';
comment on column public.asm_renseignement.rg_id is 'Clé primaire, identifiant des renseignements';
comment on column public.asm_renseignement.rg_fk_alerte_general_id is 'Clé étrangère, ID de l''alerte associée';
comment on column public.asm_renseignement.rg_circonstances is 'Renseignements sur les circonstances de l''accident';
comment on column public.asm_renseignement.rg_sensible is '(Booléen) Caractère sensible';
comment on column public.asm_renseignement.rg_mesures_prises is 'Renseignements sur les mesures prises lors de l''accident';
comment on column public.asm_renseignement.rg_mp_relevage is ' (Booléen) Mesure prise - Relevage';
comment on column public.asm_renseignement.rg_mp_collier is '(Booléen) Mesure prise - Collier';
comment on column public.asm_renseignement.rg_mp_attelle is '(Booléen) Mesure prise - Attelle';
comment on column public.asm_renseignement.rg_mp_ked is '(Booléen) Mesure prise - KED';
comment on column public.asm_renseignement.rg_mp_perche is '(Booléen) Mesure prise - Perche';
comment on column public.asm_renseignement.rg_mp_mam is '(Booléen) Mesure prise - Mam';
comment on column public.asm_renseignement.rg_mp_treuillage is '(Booléen) Mesure prise - Treuillage';
comment on column public.asm_renseignement.rg_mp_o2 is '(Booléen) Mesure prise - O2';
comment on column public.asm_renseignement.rg_mp_mid is '(Booléen) Mesure prise - Mid';
comment on column public.asm_renseignement.rg_fk_entite_secours_id is 'Clé étrangère, ID de la personne ayant suivi l''affaire';

--
-- Name: tab_config; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.asm_configuration_unite (
    cu_id integer GENERATED BY DEFAULT AS IDENTITY,
    cu_annee integer,
    cu_unite character varying(256),
    cu_code_unite character varying(10),
    cu_fk_commune_id integer, 
	PRIMARY KEY (cu_id), 
	FOREIGN KEY (cu_fk_commune_id) REFERENCES public.asm_commune (co_id) ON DELETE SET NULL
);

comment on table public.asm_configuration_unite is 'Unité gérant les alertes et les configurations (Mode avancé, configuration unité)';
comment on column public.asm_configuration_unite.cu_id is 'Clé primaire, identifiant de l''unité de configuration';
comment on column public.asm_configuration_unite.cu_annee is 'Année actuelle';
comment on column public.asm_configuration_unite.cu_unite is 'Nom de l''unité';
comment on column public.asm_configuration_unite.cu_code_unite is 'Code de l''unité';
comment on column public.asm_configuration_unite.cu_fk_commune_id is 'Clé étrangère, commune de l''unité';


--
-- Name: tab_deroulement; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.asm_deroulement (
    dr_id integer GENERATED BY DEFAULT AS IDENTITY,
    dr_fk_alerte_general_id integer NOT NULL,
	dr_actions_gdh timestamp without time zone[] NOT NULL,
    dr_actions text[],
	PRIMARY KEY (dr_id), 
	FOREIGN KEY (dr_fk_alerte_general_id) REFERENCES public.asm_alerte_general (ag_id) ON DELETE CASCADE
);

comment on table public.asm_deroulement is 'Déroulement des opérations liés à une alerte (onglet ''Déroulement'')';
comment on column public.asm_deroulement.dr_id is 'Clé primaire, identifiant du déroulement des opérations';
comment on column public.asm_deroulement.dr_fk_alerte_general_id is 'Clé étrangère, ID de l''alerte associée';
comment on column public.asm_deroulement.dr_actions_gdh is 'GDH (Groupe Date-heure) de chaque action menée lors des opérations (tableau). Entrée correspondante avec dr_actions.';
comment on column public.asm_deroulement.dr_actions is 'Liste des actions menées lors des opérations (tableau). Entrée correspondante avec dr_actions_gdh.';

--
-- Name: tab_moyens; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.asm_moyen_engage (
    mo_id integer GENERATED BY DEFAULT AS IDENTITY,
    mo_fk_alerte_general_id integer,
    mo_fk_entite_secours_id integer,
	PRIMARY KEY (mo_id), 
	FOREIGN KEY (mo_fk_alerte_general_id) REFERENCES public.asm_alerte_general (ag_id) ON DELETE CASCADE,
	FOREIGN KEY (mo_fk_entite_secours_id) REFERENCES public.asm_entite_secours (es_id) ON DELETE SET NULL
);

comment on table public.asm_moyen_engage is 'Moyen engagé pour une alerte en particulier';
comment on column public.asm_moyen_engage.mo_id is 'Clé primaire, identifiant du duo alerte-moyen engagé';
comment on column public.asm_moyen_engage.mo_fk_alerte_general_id is 'Clé étrangère, ID de l''alerte associée';
comment on column public.asm_moyen_engage.mo_fk_entite_secours_id is 'Clé étrangère, ID de l''entité de secours engagée pour la dite alerte';

--
-- Name: tab_victimes; Type: TABLE; Schema: public; Owner: admin
--
CREATE TABLE public.asm_victime (
    vi_id integer GENERATED BY DEFAULT AS IDENTITY,
    vi_fk_alerte_general_id integer,
    vi_nom character varying(256),
    vi_prenom character varying(256),
    vi_sexe character varying(1),
    vi_naissance_date timestamp without time zone,
    vi_naissance_lieu character varying(256),
    vi_fk_nationalite_id integer,
    vi_filiation character varying(256),
    vi_adresse character varying(256),
    vi_fk_commune_id integer,
    vi_telephone character varying(256),
    vi_profession character varying(256),
    vi_fk_etat_clinique_id integer,
    vi_blessures character varying(256),
    vi_fk_lieu_evacuation_id integer, 
	PRIMARY KEY (vi_id), 
	FOREIGN KEY (vi_fk_alerte_general_id) REFERENCES public.asm_alerte_general (ag_id) ON DELETE CASCADE,
	FOREIGN KEY (vi_fk_nationalite_id) REFERENCES public.asm_nationalite (na_id) ON DELETE SET NULL,
	FOREIGN KEY (vi_fk_commune_id) REFERENCES public.asm_commune (co_id) ON DELETE SET NULL,
	FOREIGN KEY (vi_fk_etat_clinique_id) REFERENCES public.asm_etat_clinique (ec_id) ON DELETE SET NULL, 
	FOREIGN KEY (vi_fk_lieu_evacuation_id) REFERENCES public.asm_lieu_evacuation(le_id) ON DELETE SET NULL
);

comment on table public.asm_victime is 'Victime';
comment on column public.asm_victime.vi_id is 'Clé primaire, identifiant de la victime';
comment on column public.asm_victime.vi_fk_alerte_general_id is 'Clé secondaire, identifiant de l''alerte associée à la victime';
comment on column public.asm_victime.vi_nom is 'Nom de la victime';
comment on column public.asm_victime.vi_prenom is 'Prénom de la victime';
comment on column public.asm_victime.vi_sexe is 'Sexe de la victime';
comment on column public.asm_victime.vi_naissance_date is 'Date de naissance de la victime';
comment on column public.asm_victime.vi_naissance_lieu is 'Lieu de naissance de la victime';
comment on column public.asm_victime.vi_fk_nationalite_id is 'Nationalité de la victime';
comment on column public.asm_victime.vi_filiation is 'Noms et prénoms de la famille de la victime';
comment on column public.asm_victime.vi_adresse is 'Adresse de la victime';
comment on column public.asm_victime.vi_fk_commune_id is 'Clé étrangère, commune d''habitation';
comment on column public.asm_victime.vi_telephone is 'Téléphone de la victime';
comment on column public.asm_victime.vi_profession is 'Profession de la victime';
comment on column public.asm_victime.vi_fk_etat_clinique_id is 'Clé étrangère, identifiant de l''état clinique';
comment on column public.asm_victime.vi_blessures is 'Liste des blessures de la victime';
comment on column public.asm_victime.vi_fk_lieu_evacuation_id is 'Clé étrangère, ID du lieu d''évacuation';

-- Ownership --
ALTER TABLE public.asm_data_exchange OWNER TO admin;
ALTER TABLE public.asm_condition_meteo OWNER TO admin;
ALTER TABLE public.asm_etat_vent OWNER TO admin;
ALTER TABLE public.asm_intervenant OWNER TO admin;
ALTER TABLE public.asm_zone_geographique OWNER TO admin;
ALTER TABLE public.asm_activite_sportive OWNER TO admin;
ALTER TABLE public.asm_blessure OWNER TO admin;
ALTER TABLE public.asm_etat_clinique OWNER TO admin;
ALTER TABLE public.asm_entite_secours OWNER TO admin;
ALTER TABLE public.asm_commune OWNER TO admin;
ALTER TABLE public.asm_lieu OWNER TO admin;
ALTER TABLE public.asm_lieu_evacuation OWNER TO admin;
ALTER TABLE public.asm_nationalite OWNER TO admin;
ALTER TABLE public.asm_massif OWNER TO admin;
ALTER TABLE public.asm_alerte_general OWNER TO admin;
ALTER TABLE public.asm_alerte_localisation OWNER TO admin;
ALTER TABLE public.asm_alerte_gestion_secours OWNER TO admin;
ALTER TABLE public.asm_alerte_accident OWNER TO admin;
ALTER TABLE public.asm_renseignement OWNER TO admin;
ALTER TABLE public.asm_configuration_unite OWNER TO admin;
ALTER TABLE public.asm_deroulement OWNER TO admin;
ALTER TABLE public.asm_moyen_engage OWNER TO admin;
ALTER TABLE public.asm_victime OWNER TO admin;

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO admin;

